apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i73o33302-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i73o33302-go 
  name: i73o33302-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i73o33302-go 
